In [3]:
import pandas as pd

In [4]:
# Read the file
df = pd.read_csv("Procurement KPI Analysis Dataset.csv")
df

,PO_ID,Supplier,Order_Date,Delivery_Date,Item_Category,Order_Status,Quantity,Unit_Price,Negotiated_Price,Defective_Units,Compliance
0,PO-00001,Alpha_Inc,2023-10-17,2023-10-25,Office Supplies,Cancelled,1176,20.13,17.81,NaN,Yes
1,PO-00002,Delta_Logistics,2022-04-25,2022-05-05,Office Supplies,Delivered,1509,39.32,37.34,235.0,Yes
2,PO-00003,Gamma_Co,2022-01-26,2022-02-15,MRO,Delivered,910,95.51,92.26,41.0,Yes
3,PO-00004,Beta_Supplies,2022-10-09,2022-10-28,Packaging,Delivered,1344,99.85,95.52,112.0,Yes
4,PO-00005,Delta_Logistics,2022-09-08,2022-09-20,Raw Materials,Delivered,1180,64.07,60.53,171.0,No
...,...,...,...,...,...,...,...,...,...,...,...
772,PO-00773,Delta_Logistics,2023-02-11,2023-02-20,Electronics,Delivered,1685,43.42,42.24,262.0,Yes
773,PO-00774,Alpha_Inc,2022-07-23,NaN,Office Supplies,Delivered,445,68.94,60.35,7.0,Yes
774,PO-00775,Gamma_Co,2022-03-19,2022-04-07,Raw Materials,Delivered,494,94.82,81.89,29.0,Yes
775,PO-00776,Beta_Supplies,2023-08-30,2023-09-11,MRO,Delivered,1306,21.05,18.27,128.0,Yes
776,PO-00777,Beta_Supplies,2023-12-09,2023-12-11,Office Supplies,Delivered,1988,105.20,93.23,187.0,Yes

In [5]:
# Check missing values before dropping
print(df.isnull().sum())

PO_ID                 0
Supplier              0
Order_Date            0
Delivery_Date        87
Item_Category         0
Order_Status          0
Quantity              0
Unit_Price            0
Negotiated_Price      0
Defective_Units     136
Compliance            0
dtype: int64

In [6]:
# Drop rows that contain at least one missing value
df = df.dropna()
df

,PO_ID,Supplier,Order_Date,Delivery_Date,Item_Category,Order_Status,Quantity,Unit_Price,Negotiated_Price,Defective_Units,Compliance
1,PO-00002,Delta_Logistics,2022-04-25,2022-05-05,Office Supplies,Delivered,1509,39.32,37.34,235.0,Yes
2,PO-00003,Gamma_Co,2022-01-26,2022-02-15,MRO,Delivered,910,95.51,92.26,41.0,Yes
3,PO-00004,Beta_Supplies,2022-10-09,2022-10-28,Packaging,Delivered,1344,99.85,95.52,112.0,Yes
4,PO-00005,Delta_Logistics,2022-09-08,2022-09-20,Raw Materials,Delivered,1180,64.07,60.53,171.0,No
5,PO-00006,Epsilon_Group,2022-08-17,2022-08-29,MRO,Delivered,1145,69.21,63.57,39.0,Yes
...,...,...,...,...,...,...,...,...,...,...,...
771,PO-00772,Beta_Supplies,2023-01-20,2023-02-02,Electronics,Delivered,226,102.47,99.16,28.0,Yes
772,PO-00773,Delta_Logistics,2023-02-11,2023-02-20,Electronics,Delivered,1685,43.42,42.24,262.0,Yes
774,PO-00775,Gamma_Co,2022-03-19,2022-04-07,Raw Materials,Delivered,494,94.82,81.89,29.0,Yes
775,PO-00776,Beta_Supplies,2023-08-30,2023-09-11,MRO,Delivered,1306,21.05,18.27,128.0,Yes
776,PO-00777,Beta_Supplies,2023-12-09,2023-12-11,Office Supplies,Delivered,1988,105.20,93.23,187.0,Yes

In [7]:
# Check again after dropping
print(df.isnull().sum())

PO_ID               0
Supplier            0
Order_Date          0
Delivery_Date       0
Item_Category       0
Order_Status        0
Quantity            0
Unit_Price          0
Negotiated_Price    0
Defective_Units     0
Compliance          0
dtype: int64

In [8]:
#Show dataset size after cleaning
print("\nDataset shape after cleaning:", df.shape)

Dataset shape after cleaning: (569, 11)

In [11]:
print(df.describe())

          Quantity  Unit_Price  Negotiated_Price  Defective_Units
count   569.000000  569.000000        569.000000       569.000000
mean   1114.029877   58.474815         53.922021        76.035149
std     639.008638   28.447759         26.392404        69.199030
min      51.000000   10.840000          9.270000         0.000000
25%     650.000000   33.250000         30.330000        27.000000
50%    1106.000000   59.040000         54.250000        50.000000
75%    1572.000000   83.730000         77.860000       101.000000
max    5000.000000  109.170000        107.390000       321.000000

In [15]:
print("Missing values after cleaning:")
print(df.isnull().sum())

print("\nZero values after cleaning:")
print((df == 0).sum())

Missing values after cleaning:
PO_ID               0
Supplier            0
Order_Date          0
Delivery_Date       0
Item_Category       0
Order_Status        0
Quantity            0
Unit_Price          0
Negotiated_Price    0
Defective_Units     0
Compliance          0
dtype: int64

Zero values after cleaning:
PO_ID               0
Supplier            0
Order_Date          0
Delivery_Date       0
Item_Category       0
Order_Status        0
Quantity            0
Unit_Price          0
Negotiated_Price    0
Defective_Units     4
Compliance          0
dtype: int64

In [ ]:
# Check for missing values
print("Missing values:\n", df.isnull().sum())

# Check the value to zero
print("\nZero values:\n", (df == 0).sum())

# Duplicate data check
print("\nDuplicate rows:", df.duplicated().sum())

Missing values:
 PO_ID               0
Supplier            0
Order_Date          0
Delivery_Date       0
Item_Category       0
Order_Status        0
Quantity            0
Unit_Price          0
Negotiated_Price    0
Defective_Units     0
Compliance          0
dtype: int64

Zero values:
 PO_ID               0
Supplier            0
Order_Date          0
Delivery_Date       0
Item_Category       0
Order_Status        0
Quantity            0
Unit_Price          0
Negotiated_Price    0
Defective_Units     4
Compliance          0
dtype: int64

Duplicate rows: 0

In [ ]:
#Save a new file after deleting data.
df.to_excel("cleaned_dataset_final.xlsx", index=False)